name = "cf-dh"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "cfdh.kytd.us.kg"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cf-dh"
# routes = [
#   { pattern = "cfdh.kytd.us.kg", custom_domain = true },
#   { pattern = "cfdh.kytd.us.kg", custom_domain = true },
#   { pattern = "cfdh.kytd.us.kg", custom_domain = true },
#   { pattern = "cfdh.kytd.us.kg", custom_domain = true },
#   { pattern = "cfdh.kytd.us.kg", custom_domain = true },
#   { pattern = "cfdh.kytd.us.kg", custom_domain = true },
#   { pattern = "cfdh.kytd.us.kg", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cf-dh"
# route = { pattern = "cfdh.kytd.us.kg", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
